title = "Airspace for Hugo"
baseURL = "https://icareerclimber.github.io/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "How It Works"
    url = "/howitworks"
  [[menu.header]]
    weight = 3
    name = "Live Demo"
    url = "/demo"
  [[menu.header]]
    weight = 4
    name = "Team"
    url = "/team"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "iCareer Climber"
    subtitle = "Giving you the data behind careers"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "iCareer Climber takes resume information and digests it to be useful information for the job seeker."
    paragraph = "The best resources for career guidance today are top 10 articles and static databases. By creating a data pipeline that processes historical career information, we are able to derive key career attributes for the user. Our work has shown promising results. The wisdom of the crowd can in fact be leveraged to guide our users to their next step."

  [params.howitworks]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Test Our Product Today"
    content = "Click below to be redirected to app."
    [params.feature.button]
      caption = "Access iCareer Climber"
      url = "http://35.233.221.248/"

  [params.call]
    enable = true
    title = "TEST OUR PRODUCT"
    [params.call.button]
      button = "test"
      url = "http://35.233.221.248/"
      text = "test"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
