title = "iCareer Climber"
baseURL = "https://icareerclimber.github.io/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "How It Works"
    url = "/howitworks"
  [[menu.header]]
    weight = 3
    name = "Team"
    url = "/team"

  [[menu.footer]]
    weight = 1
    name = "About Us"
    url = "/"
  [[menu.footer]]
    weight = 2
    name = "How It Works"
    url = "/howitworks"
  [[menu.footer]]
    weight = 3
    name = "Team"
    url = "/team"
# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "About Us"

  [params.slider]
    enable = true
    title = "iCareer Climber"
    subtitle = "Eliminate Guesswork from Your Career Planning"

  [params.wrapper]
    enable = true
    title1 = "About Us"
    italic = "iCareer Climber transforms hundreds of thousands of resumes into digestible information for the job seeker. Our tools give job seekers the power to tackle their next career move."
    paragraph1 = "Today, the best resources for career guidance are Top 10 articles and stale databases. By combining data mining, machine learning, and user experience, we have pulled together key career information for today's job seeker."
    paragraph2 = "Our work shows promising results. The wisdom of the crowd can in fact be leveraged to guide job seekers to their next move."

  [params.howitworks]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Test Our Product Today"
    content = "Click below to be redirected to app."
    [params.feature.button]
      caption = "Access iCareer Climber"
      url = "http://35.233.221.248/"

  [params.call]
    enable = true
    title = "TEST OUR PRODUCT"
    [params.call.button]
      button = "test"
      url = "http://35.233.221.248/"
      text = "test"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
